# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setGeometry(QtCore.QRect(20, 10, 611, 541))
        self.map_label.setMinimumSize(QtCore.QSize(611, 541))
        self.map_label.setMaximumSize(QtCore.QSize(611, 541))
        self.map_label.setObjectName("map_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(640, 40, 281, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radio_button_sat = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_button_sat.setObjectName("radio_button_sat")
        self.map_group = QtWidgets.QButtonGroup(MainWindow)
        self.map_group.setObjectName("map_group")
        self.map_group.addButton(self.radio_button_sat)
        self.gridLayout.addWidget(self.radio_button_sat, 2, 0, 1, 1)
        self.radio_button_gibrid = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_button_gibrid.setObjectName("radio_button_gibrid")
        self.map_group.addButton(self.radio_button_gibrid)
        self.gridLayout.addWidget(self.radio_button_gibrid, 3, 0, 1, 1)
        self.find_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.find_button.setObjectName("find_button")
        self.gridLayout.addWidget(self.find_button, 0, 1, 1, 1)
        self.radio_button_map = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_button_map.setObjectName("radio_button_map")
        self.map_group.addButton(self.radio_button_map)
        self.gridLayout.addWidget(self.radio_button_map, 1, 0, 1, 1)
        self.edit_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edit_name.setObjectName("edit_name")
        self.gridLayout.addWidget(self.edit_name, 0, 0, 1, 1)
        self.adress_label = QtWidgets.QLabel(self.centralwidget)
        self.adress_label.setGeometry(QtCore.QRect(650, 290, 201, 91))
        self.adress_label.setText("")
        self.adress_label.setObjectName("adress_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Большая задача по Maps API"))
        self.map_label.setText(_translate("MainWindow", ""))
        self.radio_button_sat.setText(_translate("MainWindow", "спутник"))
        self.radio_button_gibrid.setText(_translate("MainWindow", "гибрид"))
        self.find_button.setText(_translate("MainWindow", "найти"))
        self.radio_button_map.setText(_translate("MainWindow", "карта"))
